name: Build Toolchain

on:
  workflow_dispatch:
jobs:
  Build:
    env:
        GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    steps:
      - uses: actions/checkout@v4
      - name: Build pahole
        run: |
          sudo apt update
          sudo apt install -y \
          build-essential \
          cmake \
          git \
          flex \
          bison \
          libelf-dev \
          libdw-dev \
          libzstd-dev \
          zlib1g-dev
          git clone https://github.com/acmel/dwarves.git
          cd dwarves
          mkdir build && cd build
          cmake ..
          make
      - name: Upload to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
         name: toolchain
         path: |
          pahole
          ctfmerge
          ctudump
          codiff
          dtagnames
         if-no-files-found: error
         compression-level: 6
