name: Compile Kernel (Debug)

on:
  workflow_dispatch:
    inputs:
      brand:
        description: "Brand: Select your brand"
        required: true
        type: choice
        default: xiaomi
        options:
          - xiaomi

      soc:
        description: "SOC: Type your soc"
        required: true
        type: string
        default: "gauguin"

      clang_version:
        description: "Clang-Version: Select the clang version of ur kernel"
        required: true
        type: choice
        default: clang-r563880c
        options:
          - clang-r416183b1 #lineage-19.1 in android12-qpr3-release
          - clang-r450784d  #lineage-20.0 in android13-qpr3-release
          - clang-r487747c  #lineage-21.0 in android14-qpr3-release
          - clang-r536225   #lineage-22.2 in android15-qpr2-release
          - clang-r547379   #lineage-23.0 in android16-qpr3-release
          - clang-r563880c  #lineage-23.2 in android16-qpr3-release
          - clang-r584948   #Unrelease lineage-24.0 in androird17-qpr0-release
      kernel_source:
        description: "Kernel-Source: Kernel repo's org/user on github"
        required: true
        type: choice
        default: LineageOS
        options:
          - Manual-Type
          - LineageOS
          - crdroidandroid
          - OnePlus12R-development
          - YAAP

      kernel_source_manual:
        description: "Kernel-Source-Manual: If u selected Manual-Type in previous options, manually type ur repo's org/user on github here."
        required: false
        type: string
        default: ""

      kernel_source_format:
        description: "Source-Format: Select ur kernel source format(1 for los etc. 2 for yaap etc.)(keep default if u dont know)"
        required: true
        type: choice
        default: android_kernel
        options:
          - android_kernel
          - kernel

      kernel_branch:
        description: "Kernel-Branch: such as lineage-23.2 sixteen-qpr1 etc."
        required: true
        type: string
        default: "lineage-23.2"
        
      kernel_configs:
        description: "Kernel-Configs: Select ur kernel configs(Use Manual-Type to custom it)"
        required: true
        type: choice
        default: Manual-Type
        options:
          - Manual-Type
          - oplus-sm8150-los
          - oplus-sm8150-yaap
          - oplus-sm8250-los
          - oplus-sm8350-los
          - oplus-sm8550-los
          - oplus-sm8650-los

      kernel_configs_manual:
        description: "Kernel-Configs-Manual: If u selected Manual-Type in previous options, manually type ur kernel configs here."
        required: false
        type: string
        default: "vendor/kona-perf_defconfig"

      ksu_type:
        description: "KSU: KernelSU Version"
        required: true
        type: choice
        default: "ReSukiSU-with-susfs"
        options:
          - None
          - Official-KernelSU
          - KernelSU-Next
          - KernelSU-Next-with-susfs
          - KowSU
          - KernelSU-by-xx
          - ReSukiSU
          - ReSukiSU-with-susfs
          - SukiSUUltra NonGKI
          - SukiSUUltra-Plus NonGKI
      susfs-gki:
        description: "SUSFS-GKI: select ur kernel version(for gki)"
        required: true
        type: choice
        default: None
        options:
          - None
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12

      susfs-nongki:
        description: "SUSFS-NONGKI: select ur kernel version(for nongki)"
        required: true
        type: choice
        default: 4.19
        options:
          - None
          - 4.9
          - 4.14
          - 4.19
          - 5.4

      droidspaces:
        description: "DroidSpaces: Enable DroidSpaces"
        required: true
        type: choice
        default: 3.18-4.19
        options:
          - None
          - 5.4-6.6
          - 3.18-4.19

      has_modules_repo:
        description: "Has-Modules-Repo: Enable this ur kernel has modules repo"
        required: true
        type: boolean
        default: false

      enable_tmpfs-xattr:
        description: "TMPFS_XATTR: U can enable this if ur kernel has no CONFIG_TMPFS_XATTR=y"
        required: true
        type: boolean
        default: false

      enable_gcc:
        description: "Enable-GCC: Enable the GCC support"
        required: true
        type: boolean
        default: true
      
      enable_gcc_32bits:
        description: "Enable-GCC-32Bits: Enable the 32Bits GCC support"
        required: true
        type: boolean
        default: false

      fuck_modules_sig_protect:
        description: "Fuck-Modules-Sig-Protect: FUCK MODULES SIG Protectttt"
        required: true
        type: boolean
        default: false

      fuck_werror:
        description: "Fuck-Werror: FUCK WERROR IN CONFIGS"
        required: true
        type: boolean
        default: false

      enable_my_own_susfs_patch:
        description: "fuck susfs: fuck susfs"
        required: true
        type: boolean
        default: false

jobs:
  Kernel_CI:
    env:
        GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
          
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          bc bison flex \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          build-essential \
          lz4 \
          git \
          python3 \
          curl \
          dwarves \
          cpio \
          gcc-aarch64-linux-gnu \
          linux-tools-common
          
      - name: Clone Kernel Source
        run: |
          git clone https://github.com/oppo-source/android_kernel_oppo_sm7250.git sm7250 --depth=1 -b oppo/sm7250_s_12.1_reno4_5g
          
      - name: Download AOSP Clang
        run: |
              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-qpr1-release/clang-r416183b.tar.gz

          mkdir -p toolchains/clang-r416183b
          
          tar -xf "clang-r416183b.tar.gz" -C "toolchains/clang-r416183b" || exit 1



      - name: Include goodies
        run: |
          cd sm7250 || exit 1
          
              curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash -s main

              sed -i '170s/error/warning/g' drivers/kernelsu/Kbuild
              sed -i '81s/-dirty//g' drivers/kernelsu/Kbuild
              curl -Lo susfs.patch https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Patch/susfs_patch_to_4.19.patch || exit 1
              curl -Lo inline.sh https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/susfs_inline_hook_patches.sh || exit 1

              patch -p1 < susfs.patch || true
              bash inline.sh || true

              sed -i '/^#include <linux\/init.h>/a\
              #ifdef CONFIG_KSU_SUSFS_SUS_MOUNT\
              #include <linux/susfs_def.h>\
              \
              extern bool susfs_is_current_ksu_domain(void);\
              extern struct static_key_true susfs_is_sdcard_android_data_not_decrypted;\
              \
              #define CL_COPY_MNT_NS 0x00000100\
              #define VFSMOUNT_MNT_FLAGS_KSU_UNSHARED_MNT 0x80000000\
              #define DEFAULT_KSU_MNT_ID 500000\
              #define DEFAULT_KSU_MNT_GROUP_ID 5000\
              #endif' fs/namespace.c
 
              sed -i 's/\.handle_inode_event/.handle_event/' drivers/kernelsu/manager/pkg_observer.c

          touch ./.scmversion
         
      - name: Make Kernel Configs
        run: |
          CLANG_ROOT="${GITHUB_WORKSPACE}/toolchains/clang-r416183b/bin"
          export PATH="${CLANG_ROOT}:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-

          cd sm7250 || exit 1

            make O=out ${{ inputs.kernel_configs_manual }} 
            echo "CONFIG_KSU_SUSFS=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> out/.config
            echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> out/.config
          fi
          
      - name: Build Kernel Image
        run: |
          CLANG_ROOT="${GITHUB_WORKSPACE}/toolchains/clang-r416183b/bin"
          export PATH="${CLANG_ROOT}:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-
            
          cd sm7250 || exit 1
          
          make -j$(nproc) O=out Image 2>&1 | tee ${GITHUB_WORKSPACE}/build.log
          
      - name: Make AnyKernel3
        run: |
          ZIP_NAME="${{ inputs.soc }}_${{ inputs.kernel_source }}-${{ inputs.kernel_branch }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
          git clone https://github.com/Kernel-SU/AnyKernel3.git
          cp ${{ inputs.soc }}/out/arch/arm64/boot/Image ./Image
          cd AnyKernel3 || exit 1

          sed -i "s|ksu_supported=false|ksu_supported=true|" anykernel.sh

          zip -r9 ../"${ZIP_NAME}.zip" * -x .git

      - name: Upload to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
         name: kernel
         path: |
          *.zip
          Image
          build.log
          options.txt
         if-no-files-found: error
         compression-level: 6
